DECLARE
    V_MAX_DEPTNO OEHR_DEPARTMENTS.DEPARTMENT_ID%TYPE;
    REC_DEPARTMENT OEHR_DEPARTMENTS%ROWTYPE;
BEGIN
    SELECT MAX(DEPARTMENT_ID)
    INTO V_MAX_DEPTNO
    FROM OEHR_DEPARTMENTS;
    
    INSERT INTO OEHR_DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (V_MAX_DEPTNO + 10, 'EDUCATION');

    SELECT *
    INTO REC_DEPARTMENT
    FROM OEHR_DEPARTMENTS
    WHERE DEPARTMENT_ID = V_MAX_DEPTNO + 10;
    
    dbms_output.put_line(REC_DEPARTMENT.DEPARTMENT_ID || ' ' || REC_DEPARTMENT.DEPARTMENT_NAME || ' ' || REC_DEPARTMENT.MANAGER_ID || ' ' || REC_DEPARTMENT.LOCATION_ID);
END;